services:
  postgres:
    image: "postgres:16"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=pipeline
      - POSTGRES_PASSWORD=pipeline
      - POSTGRES_DB=pipeline

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"